name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        clean: true
        token: ${{ secrets.ACTIONS_DEMO_TOKEN }} # Use the custom PAT

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.ACTIONS_DEMO_TOKEN }}
        overwrite-settings: true

    - name: Debug - Print Environment Variables and Repository Info
      run: |
        echo "GitHub Actor: ${{ github.actor }}"
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        echo "Token Length: ${#secrets.ACTIONS_DEMO_TOKEN}"
        if [ -z "${{ secrets.ACTIONS_DEMO_TOKEN }}" ]; then
          echo "Error: ACTIONS_DEMO_TOKEN is not set or empty."
          exit 1
        else
          echo "ACTIONS_DEMO_TOKEN is set."
        fi

        # Construct the repository and packages URLs
        REPO_URL="https://github.com/${{ github.repository }}"
        PACKAGE_URL="https://maven.pkg.github.com/${{ github.repository }}"
        
        echo "Constructed Repository URL: $REPO_URL"
        echo "Constructed Packages URL: $PACKAGE_URL"

    - name: Create Maven settings.xml
      run: |
        mkdir -p $HOME/.m2
        echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
                <servers>
                  <server>
                    <id>github</id>
                    <username>${{ github.actor }}</username>
                    <password>${{ secrets.ACTIONS_DEMO_TOKEN }}</password>
                  </server>
                </servers>
              </settings>' > $HOME/.m2/settings.xml

    - name: Set up Git Credentials
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global credential.helper store
        echo "https://x-access-token:${{ secrets.ACTIONS_DEMO_TOKEN }}@github.com" > ~/.git-credentials

    - name: Update POM with Constructed URLs
      run: |
        REPO_URL="https://github.com/${{ github.repository }}"
        PACKAGE_URL="https://maven.pkg.github.com/${{ github.repository }}"
        mvn versions:set-property -Dproperty=repository.url -DnewVersion="$REPO_URL"
        mvn versions:set-property -Dproperty=distribution.url -DnewVersion="$PACKAGE_URL"

    - name: Debug - Verify Maven Settings and POM URL
      run: |
        echo "Maven settings.xml content:"
        cat $HOME/.m2/settings.xml
        
        echo "pom.xml content:"
        cat pom.xml
        
    - name: Build with Maven
      run: mvn clean package

    - name: Check for Artifact
      run: |
        if [ ! -f target/actions-demo-1.0-SNAPSHOT.jar ]; then
          echo "Artifact not found in target directory."
          exit 1
        fi

    - name: Deploy to GitHub Packages
      run: mvn deploy -X

    - name: Clear Git Credentials
      if: always()
      run: |
        git config --global --unset credential.helper
        rm -f ~/.git-credentials
