name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        clean: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Configure Maven to Use GitHub Packages
      run: |
        mkdir -p $HOME/.m2
        echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
                <servers>
                  <server>
                    <id>github</id>
                    <username>${{ github.actor }}</username>
                    <password>${{ secrets.ACTIONS_DEMO_TOKEN }}</password>
                  </server>
                </servers>
                <profiles>
                  <profile>
                    <id>github</id>
                    <repositories>
                      <repository>
                        <id>central</id>
                        <url>https://repo.maven.apache.org/maven2</url>
                      </repository>
                      <repository>
                        <id>github</id>
                        <url>https://maven.pkg.github.com/${{ github.repository }}</url>
                        <snapshots>
                          <enabled>true</enabled>
                        </snapshots>
                      </repository>
                    </repositories>
                  </profile>
                </profiles>
                <activeProfiles>
                  <activeProfile>github</activeProfile>
                </activeProfiles>
              </settings>' > $HOME/.m2/settings.xml
      env:
        ACTIONS_DEMO_TOKEN: ${{ secrets.ACTIONS_DEMO_TOKEN }}

    - name: Pull Generic Utility Package from GitHub Packages
      run: |
        mvn dependency:get -Dartifact=com.example:my-utils:1.0 \
                           -DrepoUrl=https://maven.pkg.github.com/${{ github.repository }} \
                           -s $HOME/.m2/settings.xml -X
      env:
        ACTIONS_DEMO_TOKEN: ${{ secrets.ACTIONS_DEMO_TOKEN }}

    - name: Build with Maven
      run: mvn clean package -s $HOME/.m2/settings.xml
      env:
        ACTIONS_DEMO_TOKEN: ${{ secrets.ACTIONS_DEMO_TOKEN }}

    - name: Check for Artifact
      run: |
        if [ ! -f target/my-utils-1.0.jar ]; then
          echo "Artifact not found in target directory."
          exit 1
        fi

    - name: Deploy to GitHub Packages
      run: mvn deploy -s $HOME/.m2/settings.xml -X
      env:
        ACTIONS_DEMO_TOKEN: ${{ secrets.ACTIONS_DEMO_TOKEN }}

    - name: Clear Git Credentials
      if: always()
      run: |
        git config --global --unset credential.helper
        rm -f ~/.git-credentials
